apiVersion: v1
kind: Service
metadata:
  name: boatapp-nginx
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 80
  selector:
    io.kompose.service: boatapp-nginx
status:
  loadBalancer: {}
