apiVersion: apps/v1
kind: Deployment
metadata:
  name: boatapp-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: boatapp-backend
  strategy:
    type: Recreate
  template:
    spec:
      containers:
      - env:
        - name: PGDATABASE
          value: postgres
        - name: PGHOST
          value: boatapp-postgres
        - name: PGPASSWORD
          value: devops
        - name: PGUSER
          value: postgres
        - name: REDIS_URL
          value: redis://cache
        image: sbilikiewicz/boatapp_backend
        imagePullPolicy: ""
        name: boatapp-backend
        resources: {}
        volumeMounts:
        - mountPath: /opt/app/node_modules/
          name: boatapp-backend-claim0
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: boatapp-backend-claim0
        persistentVolumeClaim:
          claimName: boatapp-backend-claim0
status: {}
