apiVersion: v1
kind: Service
metadata:
  name: boatapp-redis
spec:
  ports:
  - name: "6379"
    port: 6379
    targetPort: 6379
  selector:
    io.kompose.service: boatapp-redis
status:
  loadBalancer: {}
